-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 11:48:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exerciselooper
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exerciselooper` ;

-- -----------------------------------------------------
-- Schema exerciselooper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exerciselooper` DEFAULT CHARACTER SET utf8 ;
USE `exerciselooper` ;

-- -----------------------------------------------------
-- Table `exerciselooper`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exerciselooper`.`states` ;

CREATE TABLE IF NOT EXISTS `exerciselooper`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL,
  `slug` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exerciselooper`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exerciselooper`.`exercises` ;

CREATE TABLE IF NOT EXISTS `exerciselooper`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` CHAR(50) NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Question_status_idx` (`state_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_status`
    FOREIGN KEY (`state_id`)
    REFERENCES `exerciselooper`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exerciselooper`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exerciselooper`.`types` ;

CREATE TABLE IF NOT EXISTS `exerciselooper`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL,
  `slug` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exerciselooper`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exerciselooper`.`questions` ;

CREATE TABLE IF NOT EXISTS `exerciselooper`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NULL,
  `exercise_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_questionnaires1_idx` (`exercise_id` ASC) VISIBLE,
  INDEX `fk_questions_types1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_exercise`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `exerciselooper`.`exercises` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_types`
    FOREIGN KEY (`type_id`)
    REFERENCES `exerciselooper`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exerciselooper`.`submissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exerciselooper`.`submissions` ;

CREATE TABLE IF NOT EXISTS `exerciselooper`.`submissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exerciselooper`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exerciselooper`.`answers` ;

CREATE TABLE IF NOT EXISTS `exerciselooper`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(255) NULL,
  `question_id` INT NOT NULL,
  `submission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_questions1_idx` (`question_id` ASC) VISIBLE,
  INDEX `fk_answers_tentatives1_idx` (`submission_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions`
    FOREIGN KEY (`question_id`)
    REFERENCES `exerciselooper`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_submission`
    FOREIGN KEY (`submission_id`)
    REFERENCES `exerciselooper`.`submissions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO states(NAME,slug)
VALUES ("Building","BUILD"),("Answering","ANSWER"),("Closed","CLOSE");

INSERT INTO types(NAME,slug)
VALUES ("Single line text","SHORT"),("List of single lines","MEDIUM"),("Multi-line text","LONG");

INSERT INTO exercises(title, state_id)
VALUES ("Exercise 1",1),("Exercise 2",2),("Exercise 3",2),("Exercise 4",1), ("Exercise 5",3);

INSERT INTO questions(question,exercise_id,type_id)
VALUES ("Question 1",1,1),("Question 2",1,2),("Question 1",2,3),("Question 1",3,3),("Question 2",3,2),("Question 1",5,3);

INSERT INTO submissions(path,timestamp)
VALUES ("skjjsa",'2021-03-23 22:12:12'),("s23dfer",'2021-04-21 02:42:02'),("afdgdr",'2020-12-05 13:32:34'),("rrteee",'2021-07-03 03:23:02'),("weqeww",'2020-11-05 21:32:34');

INSERT INTO answers(answer, question_id,submission_id)
VALUES ("Answers 1",1,1),("Answers 2",2,1),("Answers 1",3,2),("Answers 1",6,3),("Answers 1",6,4),("Answers 1",6,5);