-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 11:48:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ExerciseLoop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ExerciseLoop` ;

-- -----------------------------------------------------
-- Schema ExerciseLoop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExerciseLoop` DEFAULT CHARACTER SET utf8 ;
USE `ExerciseLoop` ;

-- -----------------------------------------------------
-- Table `ExerciseLoop`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExerciseLoop`.`states` ;

CREATE TABLE IF NOT EXISTS `ExerciseLoop`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL,
  `slug` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExerciseLoop`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExerciseLoop`.`exercises` ;

CREATE TABLE IF NOT EXISTS `ExerciseLoop`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` CHAR(50) NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Question_status_idx` (`state_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_status`
    FOREIGN KEY (`state_id`)
    REFERENCES `ExerciseLoop`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExerciseLoop`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExerciseLoop`.`types` ;

CREATE TABLE IF NOT EXISTS `ExerciseLoop`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL,
  `slug` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExerciseLoop`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExerciseLoop`.`questions` ;

CREATE TABLE IF NOT EXISTS `ExerciseLoop`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NULL,
  `exercise_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_questionnaires1_idx` (`exercise_id` ASC) VISIBLE,
  INDEX `fk_questions_types1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_exercise`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `ExerciseLoop`.`exercises` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_types`
    FOREIGN KEY (`type_id`)
    REFERENCES `ExerciseLoop`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExerciseLoop`.`submissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExerciseLoop`.`submissions` ;

CREATE TABLE IF NOT EXISTS `ExerciseLoop`.`submissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExerciseLoop`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExerciseLoop`.`answers` ;

CREATE TABLE IF NOT EXISTS `ExerciseLoop`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(255) NULL,
  `question_id` INT NOT NULL,
  `submission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_questions1_idx` (`question_id` ASC) VISIBLE,
  INDEX `fk_answers_tentatives1_idx` (`submission_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions`
    FOREIGN KEY (`question_id`)
    REFERENCES `ExerciseLoop`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_submission`
    FOREIGN KEY (`submission_id`)
    REFERENCES `ExerciseLoop`.`submissions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
